-- AlterEnum
ALTER TYPE "ProductSerialStatus" ADD VALUE IF NOT EXISTS 'REPAIR';
ALTER TYPE "ProductSerialStatus" ADD VALUE IF NOT EXISTS 'DEMO';
ALTER TYPE "ProductSerialStatus" ADD VALUE IF NOT EXISTS 'INTERNAL_USE';
ALTER TYPE "ProductSerialStatus" ADD VALUE IF NOT EXISTS 'TRANSFER';

-- AlterEnum
ALTER TYPE "MovementType" ADD VALUE IF NOT EXISTS 'TRANSFER_OUT';
ALTER TYPE "MovementType" ADD VALUE IF NOT EXISTS 'TRANSFER_IN';
